services:
  - type: web
    name: backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        scope: build,runtime
      - key: JWT_SECRET
        scope: build,runtime
      - key: GOOGLE_GENAI_API_KEY
        scope: build,runtime
